version: '3.8'
services:
  weatherapp:
    volumes:
      - ./:/workshop/

    # Overrides default command so things don't shut down after the process ends.
    entrypoint: /bin/sh -c "while sleep 1000; do :; done"
 
